Refactor/auth frontend
snuhcs-course/swpp-2023-project-team-6 pull request #10
Opened 2023-10-24 18:32 UTC by yjeong-k

### PR Title: Enhance/Implement signup, login, email verification logic (frontend)

#### Related Issue(s):

#### PR Description:
Enhance signup, login logic
Implement email verification logic

##### Changes Included:
- [x] Added new feature(s)
- [ ] Fixed identified bug(s)
- [x] Updated relevant documentation

##### Notes for Reviewer:

#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

#### Additional Comments:

2023-10-24 18:43 UTC, yjeong-k commented
석찬님 제가 내일 석찬님보다 늦게 일어날 것 같아서 일단 PR과 코멘트 남깁니다..😴
수업끝나고 얘기한 부분 중
1) 백에서 받아온 에러 메시지 활용
2) 이메일을 회원가입 페이지로 넘겨주기
3) number을 code로 통일하기
등과 함께 최대한 이메일인증 코드 깔끔하게 통합해보려고 했는데
비밀번호 재설정 이메일인증 시 access 토큰 저장하는 건 더 공부해봐야할 거 같아서 아직 못했어요😭 일어나서 바로 더 해볼건데 혹시 그 전에 작업하실거면 이거 머지하고 새 브랜치 파셔도 됩니다! 토큰 저장은 auto login/refresh랑 연결될 거 같아서 제가 그쪽 브랜치에서 추가로 작업해도 될 것 같아서요!!

2023-10-25 13:11 UTC, sukchan-0811 requested changes
수고 많으셨습니다!

MainActivity, MainApplication, TokenSharedPreferences에 작업해주신 내용에 대해서는 해당 디자인 패턴에 대해서 제가 잘 몰라서 내일 수업 시간 전후로 간단하게 설명해주시면 좋을 것 같아요!

작성해드린 코멘트 이외에 추후 반영해야 할 사항으로는
1. AuthTokenRemoteSource 수정 (정말로 AuthToken을 원격 저장소에서 가져오는 DataSource 역할을 수행하도록)
2. SignupScreen / ResetPasswordScreen 내 이메일 인증 흐름 분리
등이 있을 것 같은데요, 이건 제가 자동로그인 구현 및 MainActivity/AuthActivity 분리 task를 하면서 반영해보도록 하겠습니다.

코멘트는 많지 않으니 가능하면 내일 수업 전까지 반영해주시면 좋을 것 같아요! 그러면 내일 Pref 관련 설명 듣고 문제 없으면 바로 main에 머지할 수 있을 것 같습니당,,,

2023-10-25 13:11 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/service/AuthService.kt
> +    suspend fun verify_accept_signup(
```suggestion
    suspend fun verifyAcceptSignup(
```

2023-10-25 13:11 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/SignupViewModel.kt
> +
```suggestion
```

emailInput은 안 쓰니까 지우는 게 좋을 것 같습니다!

2023-10-25 13:11 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/SignupViewModel.kt
> +    fun signUp() {
```suggestion
    fun signup(emailInput: String) {
```

1. login, signup 등은 한 단어로 통일해서 쓰는 게 가독성이 좋은 것 같습니다
2. (사용자가 이메일 인증 단계에서 입력한) emailInput이 navController로 ui level에서 전달되기 때문에 이를 viewmodel로 내려주기 위해서는 SignupScreen이 사용할 `signup()` 메소드에 파라미터를 두면 될 것 같습니다

2023-10-25 13:11 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/SignupViewModel.kt
> +                        type = SignupErrorType.PASSWORDCHECK,
```suggestion
                        type = SignupErrorType.PASSWORD_CHECK,
```

2023-10-25 13:52 UTC, paul2126 commented
코드리뷰 확인해서 수정했습니다. 꼼꼼하게 봐주셔서 감사해요!

2023-10-25 15:03 UTC, yjeong-k commented
석찬님 꼼꼼하게 리뷰해주셔서 감사드리고 명현님 리뷰 반영해주셔서 넘 감사합니다!! 최고👍

내일 SharedPreferences 외에 하나 더 같이 얘기해봤으면 하는 부분이 있어서 남겨둡니다☺️

유저가 비밀번호를 재설정하거나 회원가입을 하다가 뒤로가기를 누르면
이메일 인증을 새로 다시 진행하고 싶어서라기보단 비번재설정/회원가입을 취소하고 싶어서이지 않을까 싶어서..
뒤로가기를 눌렀을 때 초기 화면인 로그인 화면으로 넘어가게 해뒀었어요!
(이부분에 대해 어떻게 생각하시는지 궁금합니다)

ResetPasswordScreen과 SignupScreen에서 onBackClick을 navigateUp()으로 하면 뒤로가기 버튼을 눌렀을 때 다시 이메일 인증을 하는 화면으로 갈텐데 지금은 그 화면이 아래와 같이 나옵니다!!
<img width="230" alt="스크린샷 2023-10-25 오후 11 46 03" src="https://github.com/snuhcs-course/swpp-2023-project-team-6/assets/65206075/91914b5c-567d-4930-9840-0fe0728feb95">
지금 구현으로는 이메일 수정이나 인증번호를 다시 보내는 게 막혀있고, 백 구현상 인증에 한번 성공한 인증번호는 재사용할 수도 없어서
유저에게 이메일 인증을 새로하게 하려면 viewModel구현쪽도 함께 수정을 해야할 것 같아요..! 내일 같이 얘기해보고 제가 반영하여 수정하겠습니다!

2023-10-25 15:13 UTC, sukchan-0811 commented
> 석찬님 꼼꼼하게 리뷰해주셔서 감사드리고 명현님 리뷰 반영해주셔서 넘 감사합니다!! 최고👍
> 
> 내일 SharedPreferences 외에 하나 더 같이 얘기해봤으면 하는 부분이 있어서 남겨둡니다☺️
> 
> 유저가 비밀번호를 재설정하거나 회원가입을 하다가 뒤로가기를 누르면 이메일 인증을 새로 다시 진행하고 싶어서라기보단 비번재설정/회원가입을 취소하고 싶어서이지 않을까 싶어서.. 뒤로가기를 눌렀을 때 초기 화면인 로그인 화면으로 넘어가게 해뒀었어요! (이부분에 대해 어떻게 생각하시는지 궁금합니다)
> 
> ResetPasswordScreen과 SignupScreen에서 onBackClick을 navigateUp()으로 하면 뒤로가기 버튼을 눌렀을 때 다시 이메일 인증을 하는 화면으로 갈텐데 지금은 그 화면이 아래와 같이 나옵니다!! <img alt="스크린샷 2023-10-25 오후 11 46 03" width="230" src="https://user-images.githubusercontent.com/65206075/278051465-91914b5c-567d-4930-9840-0fe0728feb95.png"> 지금 구현으로는 이메일 수정이나 인증번호를 다시 보내는 게 막혀있고, 백 구현상 인증에 한번 성공한 인증번호는 재사용할 수도 없어서 유저에게 이메일 인증을 새로하게 하려면 viewModel구현쪽도 함께 수정을 해야할 것 같아요..! 내일 같이 얘기해보고 제가 반영하여 수정하겠습니다!

아 이거 SignupScreen안에 (1. 이메일 인증 -> 2. 회원가입) 이렇게 넘어가게 구성해놓으면 (기존의 이메일 인증 UI 및 로직을 SignupScreen & SignupViewModel에 통일하고, UiState에 isEmailVerified: Boolean 같은 변수를 둬서 흐름을 통제하는 방식) `navigateUp()`하면 로그인 화면으로 이동할 수 있을 것 같습니다!

2023-10-25 15:14 UTC, sukchan-0811 approved these changes

2023-10-26 00:26 UTC, yjeong-k commented
> > 석찬님 꼼꼼하게 리뷰해주셔서 감사드리고 명현님 리뷰 반영해주셔서 넘 감사합니다!! 최고👍
> > 내일 SharedPreferences 외에 하나 더 같이 얘기해봤으면 하는 부분이 있어서 남겨둡니다☺️
> > 유저가 비밀번호를 재설정하거나 회원가입을 하다가 뒤로가기를 누르면 이메일 인증을 새로 다시 진행하고 싶어서라기보단 비번재설정/회원가입을 취소하고 싶어서이지 않을까 싶어서.. 뒤로가기를 눌렀을 때 초기 화면인 로그인 화면으로 넘어가게 해뒀었어요! (이부분에 대해 어떻게 생각하시는지 궁금합니다)
> > ResetPasswordScreen과 SignupScreen에서 onBackClick을 navigateUp()으로 하면 뒤로가기 버튼을 눌렀을 때 다시 이메일 인증을 하는 화면으로 갈텐데 지금은 그 화면이 아래와 같이 나옵니다!! <img alt="스크린샷 2023-10-25 오후 11 46 03" width="230" src="https://user-images.githubusercontent.com/65206075/278051465-91914b5c-567d-4930-9840-0fe0728feb95.png"> 지금 구현으로는 이메일 수정이나 인증번호를 다시 보내는 게 막혀있고, 백 구현상 인증에 한번 성공한 인증번호는 재사용할 수도 없어서 유저에게 이메일 인증을 새로하게 하려면 viewModel구현쪽도 함께 수정을 해야할 것 같아요..! 내일 같이 얘기해보고 제가 반영하여 수정하겠습니다!
> 
> 아 이거 SignupScreen안에 (1. 이메일 인증 -> 2. 회원가입) 이렇게 넘어가게 구성해놓으면 (기존의 이메일 인증 UI 및 로직을 SignupScreen & SignupViewModel에 통일하고, UiState에 isEmailVerified: Boolean 같은 변수를 둬서 흐름을 통제하는 방식) `navigateUp()`하면 로그인 화면으로 이동할 수 있을 것 같습니다!

아항 넵 이해했습니다!! 설명 감사합니다!

2023-10-26 11:16 UTC, merged