:sparkles: Implement TTS feature
snuhcs-course/swpp-2023-project-team-6 pull request #13
Opened 2023-10-28 12:03 UTC by paul2126

### PR Title: Implement TTS feature

#### Related Issue(s):

#### PR Description:
- Implemented TTS screen
- Currently pressing guest login button connects to TTS screen
- Changed the textfield to be scrollable

##### Changes Included:
- [x] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation

##### Notes for Reviewer:
Any specific instructions or points to be considered by the
reviewer.

#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

#### Additional Comments:
Add any other comments or information that might be useful for the
review process.

2023-10-28 12:30 UTC, sukchan-0811 requested changes
1. 재생 버튼 / 정지 버튼 둘 중 하나만 보이게 구현
2. viewmodel -> repository -> datasource 흐름 유지

이 두 개를 해주시면 좋을 것 같은데 일단은 데모를 위해서 1이 더 급하긴 합니다!

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/SpeechBuddyApp.kt
> +                    navController.navigate("texttospeech")
```suggestion
                    navController.navigate("text_to_speech")
```

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +        )
`state.update` 써주실 수는 없나요?

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/ui/models/TextToSpeechUiState.kt
> +)
enum class로 PLAY, STOPPED 이런 식으로 왔다갔다하게 하면 처리가 더 편할 것 같습니다

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/landing/LandingScreen.kt
> +        LandingScreen(onLoginClick = {}, onGuestClick = {})
```suggestion
        LandingScreen(onGuestClick = {}, onLoginClick = {})
```

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/SpeechBuddyApp.kt
> +        composable("texttospeech"){
```suggestion
        composable("text_to_speech"){
```

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeach/TextToSpeachScreen.kt
Speach -> speech로 모두 바꿔주세요!

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeach/TextToSpeachScreen.kt
> +                shape = RoundedCornerShape(10.dp)
다른 페이지들과의 디자인 통일성을 위해서 여기도 focus 시에 초록색이 아니라 파란색 테두리가 뜨면 좋을 것 같아요

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeach/TextToSpeachScreen.kt
> +                    .defaultMinSize(minHeight = 300.dp)
```suggestion
```

밑에서 height가 그냥 300.dp로 고정되어서 이 부분은 필요 없을 것 같습니다

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeach/TextToSpeachScreen.kt
> +                .padding(25.dp)
```suggestion
                .padding(24.dp)
```

2023-10-28 12:30 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeach/TextToSpeachScreen.kt
> +import android.text.method.ScrollingMovementMethod
```suggestion
```

2023-10-29 02:25 UTC, sukchan-0811 requested changes

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeech/TextToSpeechScreen.kt
> +            }
```suggestion
            TextToSpeechButton(
                buttonStatus = uiState.buttonStatus,
                onPlay = { viewModel.ttsStart(context) },
                onStop = { viewModel.ttsStop() }
            )
```

이 부분 너무 코드가 길어서 따로 빼면 좋을 것 같아요!

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeech/TextToSpeechScreen.kt
> +}
```suggestion
}

@Composable
private fun TextToSpeechButton(
    buttonStatus: ButtonStatusType,
    onPlay: () -> Unit,
    onStop: () -> Unit
) {
    val textToSpeechButtonColors = ButtonDefaults.buttonColors(
        containerColor = Color.Transparent,
        contentColor = MaterialTheme.colorScheme.onBackground
    )

    when (buttonStatus) {
        ButtonStatusType.PLAY -> Button(
            onClick = onPlay,
            colors = textToSpeechButtonColors
        ) {
            Text(
                style = MaterialTheme.typography.headlineMedium,
                text = stringResource(id = R.string.play_text)
            )
            Icon(
                Icons.Filled.PlayArrow,
                contentDescription = stringResource(id = R.string.play_text),
                modifier = Modifier.size(36.dp)
            )
        }

        ButtonStatusType.STOP -> Button(
            onClick = onStop,
            colors = textToSpeechButtonColors
        ) {
            Text(
                style = MaterialTheme.typography.headlineMedium,
                text = stringResource(id = R.string.stop_text)
            )
            Icon(
                painterResource(R.drawable.stop_icon),
                contentDescription = stringResource(id = R.string.stop_text),
                modifier = Modifier.size(36.dp)
            )
        }
    }
}
```

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/ui/models/TextToSpeechUiState.kt
> +    val isButtonEnabled: ButtonStatusType = ButtonStatusType.PLAY
```suggestion
    val buttonStatus: ButtonStatusType = ButtonStatusType.PLAY
```

변수명 `is~~?`은 보통 Boolean Type에 써서 조금 더 직관적인 이름으로 바꾸면 좋을 것 같습니다!

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +
```suggestion

private fun clearText() {
    textInput = ""
}

```

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +                isButtonEnabled = ButtonStatusType.STOP
```suggestion
                buttonStatus = ButtonStatusType.STOP
```

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +                                    isButtonEnabled = ButtonStatusType.PLAY
```suggestion
                                    buttonStatus = ButtonStatusType.PLAY
```

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +                                    isButtonEnabled = ButtonStatusType.PLAY
```suggestion
                                    buttonStatus = ButtonStatusType.PLAY
```

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +                            }
```suggestion
                            }
                            clearText()
```

재생이 끝나고 텍스트가 지워지면 좋을 것 같아서 추가했습니다!

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +                                    isButtonEnabled = ButtonStatusType.PLAY
```suggestion
                                    buttonStatus = ButtonStatusType.PLAY
```

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/TextToSpeechViewModel.kt
> +                        isButtonEnabled = ButtonStatusType.PLAY
```suggestion
                        buttonStatus = ButtonStatusType.PLAY
```

2023-10-29 02:25 UTC, sukchan-0811 commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="pause_text">일시정지</string>
```suggestion
```

2023-10-29 08:24 UTC, paul2126 reviewed
변경사항 다 적용했습니다! 
버튼 뺄 때 context랑 변수를 다 내려주는 방식을 생각했는데 보여주신 방식이 훨씬 깔끔해서 그대로 적용했습니다.

2023-10-29 11:22 UTC, yjeong-k commented
민영님이 말씀해주신 게 있어서 반영해서 커밋 간단한 거 하나 추가했습니다!
다른 브랜치 파기가 그래서..ㅎㅎ 여기다 같이 올리게되었어요
isValidEmail() 자체가 empty input 체크를 해줘서 수정했습니다

2023-10-29 15:17 UTC, sukchan-0811 approved these changes

2023-10-29 15:31 UTC, merged