Feat/reset password frontend
snuhcs-course/swpp-2023-project-team-6 pull request #16
Opened 2023-10-29 11:59 UTC by paul2126

### PR Title: [Descriptive title summarizing the change]

#### Related Issue(s):

#### PR Description:
- Implement reset password logic
- After password reset, moves to login page

##### Changes Included:
- [x] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation

##### Notes for Reviewer:
Any specific instructions or points to be considered by the
reviewer.

#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

#### Additional Comments:
Add any other comments or information that might be useful for the
review process.

2023-10-29 15:37 UTC, sukchan-0811 reviewed
앞에 PR 두 개가 main에 머지돼서 일단 `git main merge` 해주세요!

상징 선택 페이지 UI 작업 완료되는대로 최대한 빨리 리뷰하겠습니다 ㅠㅠ

2023-10-29 16:57 UTC, paul2126 commented
머지 완료했습니다!

2023-11-01 09:22 UTC, sukchan-0811 requested changes

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="resset_password_error">비밀번호 길이 및 재대로 입력했는지 확인해주세요</string>
```suggestion
```
이거 아무데서도 안 쓰이는 것 같은데 맞나요?

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/resetpassword/ResetPasswordScreen.kt
> +                    isError = isError,
```suggestion
                    isError = isError,
                    isValid = uiState.isValidPassword,
```

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/resetpassword/ResetPasswordScreen.kt
> +                    isError = isError,
```suggestion
                    isError = isError,
                    isValid = uiState.isValidPassword,
```

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/resetpassword/ResetPasswordScreen.kt
>                      isEnabled = true,
```suggestion
                    isError = isError,
```

isEnabled는 어차피 default value가 true여서 삭제했습니다

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +    val uiState: StateFlow<ResetPasswordUiState> = _uiState.asStateFlow()
```suggestion
    val uiState: StateFlow<ResetPasswordUiState> = _uiState.asStateFlow()
    
```

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +    }
```suggestion
    private fun clearInputs() {
        passwordInput = ""
        passwordCheckInput = ""
    }
```

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +                        Status.SUCCESS -> {
```suggestion
                    when (result.status) {
                        Status.LOADING -> {}
                    
                        Status.SUCCESS -> {
```

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +                        else -> {}
```suggestion
```

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +                        Status.SUCCESS -> {
when 문을 쓸 때는 가능한 모든 상태를 써주는 것이 좋습니다

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +}
```suggestion
                }
                clearInputs()
            }
        }
    }
}
```

지금은 에러가 나도 사용자가 쓴 인풋이 자동으로 지워져서 서버로 요청이 갈 때에만 지워지는 것으로 바꿨습니다

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +                accessToken = "Bearer $accessToken"
accessToken 받아서 헤더에 'Bearer accessToken' 다는 걸 viewmodel이 아니라 data layer에서 처리하면 더 좋을 것 같은데요... 앱 내에 저장되어 있는 accessToken을 찾는 것부터 repository 단에서 하는 것으로 구현하면 더 좋을 듯 합니다

2023-11-01 09:22 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +                accessToken = "Bearer $accessToken"
앞에 Bearer prefix 다는 건 interceptor 같은 걸 사용해서 처리하는 거 더 깔끔할 것 같아요 다른 API에서도 이 작업을 계속 반복적으로 하게 될 테니 추상화시키는 편이 나을 것 같습니다

2023-11-01 09:33 UTC, paul2126 commented on frontend/app/src/main/res/values/strings.xml
> +    <string name="resset_password_error">비밀번호 길이 및 재대로 입력했는지 확인해주세요</string>
서버 요청을 하고 어떤 이유에서 든지 에러가 났다면 뜨는 구문인데 에러가 났다는 것을 직접 명시할께요

2023-11-01 09:36 UTC, paul2126 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +                        else -> {}
어떤 변경 사항인가요?

2023-11-01 09:42 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +    val uiState: StateFlow<ResetPasswordUiState> = _uiState.asStateFlow()
아 uiState 선언한 부분하고 input들 선언한 부분 구분했으면 좋겠어서 공백 줄 추가했습니다!

2023-11-01 09:42 UTC, sukchan-0811 commented on frontend/app/src/main/java/com/example/speechbuddy/viewmodel/ResetPasswordViewModel.kt
> +                        else -> {}
LOADING일 때의 처리를 명시해주어서 else case가 필요 없습니다

2023-11-01 15:46 UTC, sukchan-0811 requested changes
Interceptor 구현 레퍼런스가 많이 없어서 어려웠을 것 같은데 빨리 작업해주신 것 같아서 감사드립니다. 정말 수고하셨습니다!!

2023-11-01 16:13 UTC, sukchan-0811 approved these changes

2023-11-01 16:14 UTC, merged