:recycle: Refactor tts screen and auto deletion
snuhcs-course/swpp-2023-project-team-6 pull request #36
Opened 2023-11-10 08:20 UTC by prime2do

### PR Title: Refactor tts screen and auto deletion

#### Related Issue(s):

#### PR Description:
Removed auto deletion. Added manual deletion button, which is activated when the speech is not being spoken. Reduced the size of textfield.

##### Changes Included:
- [x] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation

##### Notes for Reviewer:

#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

#### Additional Comments:

2023-11-11 05:21 UTC, sukchan-0811 requested changes
스크린에서 재생하기 버튼이랑 지우기 버튼 UI 조금 바꾸면 좋을 것 같아요
일단 지금 텍스트랑 아이콘이랑 vertical alignment가 안 맞고
지우기 버튼은 텍스트가 비어있을 때는 비활성화(실제로 비활성화 + 누를 수 없다는 걸 사용자에게 표시)하면 좋을 것 같습니다
지금은 TextClearButton도 TTSButton이랑 똑같은 buttonstatus랑 onplay, onstop 인자를 받는데 이 부분을 수정해야 할 것 같아요!

2023-11-15 08:48 UTC, paul2126 requested changes
버튼이 눌렸을 때 위아래 모션 효과 높이가 같으면 좋을 것 같아요

2023-11-15 08:48 UTC, paul2126 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeech/TextToSpeechScreen.kt
> +    }
hiltviewmodel사용해서 preview는 지워주셔도 될 것 같습니다

2023-11-15 08:48 UTC, paul2126 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/texttospeech/TextToSpeechScreen.kt
>                      colors = TextFieldDefaults.outlinedTextFieldColors(
focused 됐을 때 초록색으로 바꿔주시면 됩니다

2023-11-15 08:57 UTC, paul2126 approved these changes

2023-11-15 09:29 UTC, sukchan-0811 approved these changes

2023-11-15 09:46 UTC, merged