상징 생성 스크린 & 로직
snuhcs-course/swpp-2023-project-team-6 pull request #45
Opened 2023-11-16 16:59 UTC by yjeong-k

### PR Title: 상징 생성 스크린 & 로직 구현

#### Related Issue(s):

#### PR Description:
상징 생성 스크린 구현
상징 생성 뷰모델 구현
상징 생성 후 서버에 백업하기 위하여 필요한 MySymbolDto, Mapper, Repository, Service 등 구현
상징 생성 성공/실패에 따른 notification (via toast)
게스트모드 / 로그인모드에 따른 처리 로직 구분

[Provide a brief summary of the changes made.]

##### Changes Included:
- [x] Added new feature(s)
- [x] Fixed identified bug(s)
- [ ] Updated relevant documentation

##### Notes for Reviewer:

#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

#### Additional Comments:

2023-11-17 15:05 UTC, paul2126 requested changes
신경쓸 부분도 많았을텐데 프론트 백 같이 보시고 진짜 고생 많으셨습니다! 
상징 추가하는 것은 괜찮아 보이고 나중에 저희가 다시 브랜치 파서  weighttable 갱신하고, 바뀐 symbol repo& symbol dao 만 테스트 하면 될 것 같습니다.

2023-11-17 15:24 UTC, yjeong-k commented on frontend/app/src/main/java/com/example/speechbuddy/compose/symbolcreation/SymbolCreationScreen.kt
넵!! 반영하여 커밋 올렸습니다 감사합니다☺️

2023-11-17 15:29 UTC, yjeong-k commented
ㅎㅎㅎ아닙니닷 그렇게 말씀해주셔서 정말 감사해요!!
명현님께서야말로 꼼꼼하게 리뷰해주시느라 고생많으셨어요 감사합니다!!
추후 진행 사항도 인지하였습니다! 좋습니다🫡👍

2023-11-19 01:49 UTC, paul2126 approved these changes

2023-11-19 01:50 UTC, merged