Feat/settings
snuhcs-course/swpp-2023-project-team-6 pull request #53
Opened 2023-11-21 11:40 UTC by 89645321

### PR Title: 세팅 로직 구현

#### Related Issue(s):
아직 덜 했지만 브랜치가 너무 커지고 있는 것 같아서 한 번 올립니다. 로그아웃 및 회원탈퇴 시 회원정보 삭제, 자동 백업, 상징 목록 관리 페이지는 아직 안 된 상태입니다.

#### PR Description:
- 로그아웃 시 백업 확인 alertdialog 구현
- 수동 백업 구현
- 다크 모드 구현
- 시작 메뉴 선택 구현
- 저작권 정보 페이지 추가

##### Changes Included:
- [v] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation

##### Notes for Reviewer:
로그인 후 앱을 한 번 껐다 켜면 게스트모드로 들어가지니 리뷰할 때 참고 부탁드립니다.

#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

#### Additional Comments:

2023-11-21 14:46 UTC, paul2126 requested changes
파일 바꾸실 곳 많으셨는데 고생 많으셨습니다! 테스트 하면서 버그로 보이는 것들 작성해놓았습니다

1. 설정 하위 메뉴 (예: 버전정보)에서 다른 스크린으로 이동했다가 다시 설정으로 돌아가면 모든 메뉴가 보이는 스크린이 아니라 "디스플레이 설정"이 처음으로 뜨게 됩니다. 해당 상황은 디스플레이 설정에서 다크모드를 한번이라도 껐다 키면 발생하는 것 같습니다
2. 게스트 모드에서 나가기 버튼이 하단 바와 겹치고 있어서 조금 올리면 좋을 것 같습니다
3. 로그아웃 버튼을 눌렀을때 첫번제 alert dialog가 나오는데 '로그아웃' '백업'을 선택하지 않고 다른 곳을 누르면 다른 alert dialog가 나오면서 로그아웃 여부를 다시 물어봅니다. 
4. 로그아웃 할때 백업을 진행하면 설정 백업 메뉴에서 마지막 백업 날짜가 갱신 안 됩니다.
5. 백업을 진행할 때 데이터로 연결되어있으면 실패합니다 (해당 문제는 상징 생성할때도 똑같이 나타나고 있어서 저희 retrofit 연결 방식을 다시 봐야할 것 같습니다.)

2023-11-21 14:46 UTC, paul2126 commented on frontend/app/src/main/java/com/example/speechbuddy/HomeActivity.kt
> +import android.util.Log
log하고 context는 안 써서 제거해도 될 것 같아요
```suggestion
import android.content.Intent
import android.os.Bundle
```

2023-11-21 14:46 UTC, paul2126 commented on frontend/app/src/main/java/com/example/speechbuddy/compose/settings/SettingsScreen.kt
> +import android.util.Log
```suggestion
```

2023-11-21 14:46 UTC, paul2126 commented on frontend/app/src/main/java/com/example/speechbuddy/repository/SettingsRepository.kt
> +import kotlinx.coroutines.flow.collect
```suggestion
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import com.example.speechbuddy.data.local.SettingsPrefsManager
import com.example.speechbuddy.data.remote.models.SettingsBackupDto
import com.example.speechbuddy.domain.SessionManager
import com.example.speechbuddy.service.BackupService
import com.example.speechbuddy.ui.models.InitialPage
import com.example.speechbuddy.utils.Resource
import com.example.speechbuddy.utils.ResponseHandler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
```
안 쓰이는 import 제거했습니다

2023-11-22 08:57 UTC, 89645321 commented
> 파일 바꾸실 곳 많으셨는데 고생 많으셨습니다! 테스트 하면서 버그로 보이는 것들 작성해놓았습니다
> 
> 1. 설정 하위 메뉴 (예: 버전정보)에서 다른 스크린으로 이동했다가 다시 설정으로 돌아가면 모든 메뉴가 보이는 스크린이 아니라 "디스플레이 설정"이 처음으로 뜨게 됩니다. 해당 상황은 디스플레이 설정에서 다크모드를 한번이라도 껐다 키면 발생하는 것 같습니다
> 2. 게스트 모드에서 나가기 버튼이 하단 바와 겹치고 있어서 조금 올리면 좋을 것 같습니다
> 3. 로그아웃 버튼을 눌렀을때 첫번제 alert dialog가 나오는데 '로그아웃' '백업'을 선택하지 않고 다른 곳을 누르면 다른 alert dialog가 나오면서 로그아웃 여부를 다시 물어봅니다.
> 4. 로그아웃 할때 백업을 진행하면 설정 백업 메뉴에서 마지막 백업 날짜가 갱신 안 됩니다.
> 5. 백업을 진행할 때 데이터로 연결되어있으면 실패합니다 (해당 문제는 상징 생성할때도 똑같이 나타나고 있어서 저희 retrofit 연결 방식을 다시 봐야할 것 같습니다.)

꼼꼼하게 다 체크해주셔서 감사합니다! 다 해결해서 커밋했으니 확인 부탁드려요!

1. 이거 해결은 했는데 해결하면서 또 다른 문제를 하나 발견했습니다. 세팅 화면에서 세부 메뉴로 들어가기 -> 하단 바에서 상징 선택 등 다른 메뉴 선택(메인 세팅 화면으로 나오지 않고 바로 누름) -> 하단 바에서 세팅 메뉴 선택을 하면 애니메이션이 이상하게 튑니다ㅋㅋㅠㅠ 기능상 문제는 없는데 보기는 안 좋네요 원리도 해결방법도 모르겠고 큰 문제는 아니라 그냥 뒀습니다

4. 이거 하면서 자동 백업 여부를 서버에 백업을 안 하고 있다는 사실을 깨달았는데....이것도 크게 중요한 건 아니라 그냥 뒀습니다

5. 의심되는 부분을 지워봤는데 제가 갤럭시가 아니라 데이터로 확인할 수가 없습니다ㅠㅠ한번 테스트해봐주시면 감사하겠습니다!

2023-11-23 05:24 UTC, paul2126 commented
1. 저도 확인해봤는데 항상 튀는게 아니라서 까다로워 보이네요...
2. 넵넵 나중에 여유가 되면 수정하는걸로 하고 이슈쪽에 넣어놓기만 할께요
3. 작동 잘  됩니다! 인터넷 확인부분 코드를 다시 봐야겠네요
4. 저희 설정창이 세부화면에서 최상단 설정창으로 가기는 하는데 여전히 디스플레이 설정창을 보여줬다가 바뀌는데 해당 버그 고치는게 가능할까요?

2023-11-23 05:25 UTC, paul2126 approved these changes
> 꼼꼼하게 다 체크해주셔서 감사합니다! 다 해결해서 커밋했으니 확인 부탁드려요!
> 1. 이거 해결은 했는데 해결하면서 또 다른 문제를 하나 발견했습니다. 세팅 화면에서 세부 메뉴로 들어가기 -> 하단 바에서 상징 선택 등 다른 메뉴 선택(메인 세팅 화면으로 나오지 않고 바로 누름) -> 하단 바에서 세팅 메뉴 선택을 하면 애니메이션이 이상하게 튑니다ㅋㅋㅠㅠ 기능상 문제는 없는데 보기는 안 좋네요 원리도 해결방법도 모르겠고 큰 문제는 아니라 그냥 뒀습니다
> 4. 이거 하면서 자동 백업 여부를 서버에 백업을 안 하고 있다는 사실을 깨달았는데....이것도 크게 중요한 건 아니라 그냥 뒀습니다
> 5. 의심되는 부분을 지워봤는데 제가 갤럭시가 아니라 데이터로 확인할 수가 없습니다ㅠㅠ한번 테스트해봐주시면 감사하겠습니다!

1. 저도 확인해봤는데 항상 튀는게 아니라서 까다로워 보이네요...
2. 넵넵 나중에 여유가 되면 수정하는걸로 하고 이슈쪽에 넣어놓기만 할께요
3. 작동 잘  됩니다! 인터넷 확인부분 코드를 다시 봐야겠네요
4. 저희 설정창이 세부화면에서 최상단 설정창으로 가기는 하는데 여전히 디스플레이 설정창을 보여줬다가 바뀌는데 해당 버그 고치는게 가능할까요?

2023-11-23 05:30 UTC, merged