Feat/Retreive info on login
snuhcs-course/swpp-2023-project-team-6 pull request #62
Opened 2023-11-23 22:44 UTC by paul2126

### PR Title: Retreive info on login

#### Related Issue(s):

#### PR Description:
- Retreive info after login 
    - user profile
    - favorite symbols
    - custom symbols
    - settings
    - weight table
    - symbol image

##### Changes Included:
- [x] Added new feature(s)
- [ ] Fixed identified bug(s)
- [ ] Updated relevant documentation

##### Notes for Reviewer:
Any specific instructions or points to be considered by the
reviewer.

#### Reviewer Checklist:
- [ ] Code is written in clean, maintainable, and idiomatic form.
- [ ] Automated test coverage is adequate.
- [ ] All existing tests pass.
- [ ] Manual testing has been performed to ensure the PR works as expected.
- [ ] Code review comments have been addressed or clarified.

#### Additional Comments:
Add any other comments or information that might be useful for the
review process.

2023-11-24 14:32 UTC, 89645321 requested changes
앱을 처음 켠 후 새로 만든 계정으로 로그인하니 처음 상징을 눌렀을 때 앱이 종료되는 버그가 있습니다.. 메인 브랜치에서는 없는 버그인 것도 확인했습니다
로그인 시 정보를 잘 받아오는 것은 확인했습니다! initial page 부분만 한번만 더 확인 부탁드립니다 일단 확실히 확인했을 때에는 문제 없었는데 다른 부분을 확인하느라 initial page에 신경을 못 썼을 때 반대로 떴던 것 같기도 해서요..막상 테스트하려고 보면 잘 떠서 확신이 없네요
그리고 특별히 남기는 이유가 없다면 로그 지워서 올려주세요!

2023-11-24 16:56 UTC, paul2126 commented
> 앱을 처음 켠 후 새로 만든 계정으로 로그인하니 처음 상징을 눌렀을 때 앱이 종료되는 버그가 있습니다.. 메인 브랜치에서는 없는 버그인 것도 확인했습니다 로그인 시 정보를 잘 받아오는 것은 확인했습니다! initial page 부분만 한번만 더 확인 부탁드립니다 일단 확실히 확인했을 때에는 문제 없었는데 다른 부분을 확인하느라 initial page에 신경을 못 썼을 때 반대로 떴던 것 같기도 해서요..막상 테스트하려고 보면 잘 떠서 확신이 없네요 그리고 특별히 남기는 이유가 없다면 로그 지워서 올려주세요!

말씀해주신 현상 확인하고 고쳤어요! 다운받은 db를 교체하는 과정에서 기존 db를 날리고 추가가 안 되는 버그였습니다... 그 외에 테스트 해봤을 때 별다른 문제가 발견되지는 않았지만 혹시 모르니 한번 더 확인 부탁드릴께요!

2023-11-25 01:13 UTC, 89645321 commented on frontend/app/src/main/java/com/example/speechbuddy/repository/WeightTableRepository.kt
> +        Log.d("test", "inside replace")
```suggestion
```

2023-11-25 01:13 UTC, 89645321 commented on frontend/app/src/main/java/com/example/speechbuddy/repository/WeightTableRepository.kt
> +import android.util.Log
```suggestion
```

2023-11-25 01:13 UTC, 89645321 commented on frontend/app/src/main/java/com/example/speechbuddy/repository/SettingsRepository.kt
> +import android.util.Log
```suggestion
```

2023-11-25 01:14 UTC, 89645321 commented on frontend/app/src/main/java/com/example/speechbuddy/repository/SettingsRepository.kt
> +                    Log.d("test", "initialPage: $initialPage")
```suggestion
```

2023-11-25 01:16 UTC, 89645321 reviewed
확인했습니다!

2023-11-25 06:24 UTC, paul2126 commented
올려주신 변경사항도 반영 완료했습니다!

2023-11-25 07:28 UTC, 89645321 approved these changes

2023-11-25 07:28 UTC, merged